# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uxvalidator < Formula
  desc "CLI for UX Validator — automated UX quality validation"
  homepage "https://deltix.ai"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janusfidel/deltix-cli/releases/download/v0.1.0/uxvalidator_darwin_amd64.tar.gz"
      sha256 "6fd2ca62f13eaf1a3c649bab20a110f6c0fef09779604f1cbdbfca42d72f3791"

      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janusfidel/deltix-cli/releases/download/v0.1.0/uxvalidator_darwin_arm64.tar.gz"
      sha256 "8e63856ef9812d310af143450e45b8d4fccdccf76be6c6ef0b1adda7e5116473"

      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janusfidel/deltix-cli/releases/download/v0.1.0/uxvalidator_linux_amd64.tar.gz"
      sha256 "fd494a376e3a29d7bd58bf9299a12e2caebe28d212266a7be44ad878e1649cb1"
      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janusfidel/deltix-cli/releases/download/v0.1.0/uxvalidator_linux_arm64.tar.gz"
      sha256 "53346c1c09754ca8cf0217dd3fd07c0df84dd242258dfbe5f058d868e485b6fe"
      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
  end
end
