# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uxvalidator < Formula
  desc "CLI for UX Validator — automated UX quality validation"
  homepage "https://deltix.ai"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whitingdeltix/deltix-cli/releases/download/v0.1.1/uxvalidator_darwin_amd64.tar.gz"
      sha256 "e1d8a88428352f6b2440ee17e9ef4051405bb3833492a74ed3bc943b7c8566c3"

      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whitingdeltix/deltix-cli/releases/download/v0.1.1/uxvalidator_darwin_arm64.tar.gz"
      sha256 "927ff855565df47e523ea95333fb3c7bd438cd60b0f787633cb5fcd19fe4e2ce"

      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whitingdeltix/deltix-cli/releases/download/v0.1.1/uxvalidator_linux_amd64.tar.gz"
      sha256 "bb5473b8ff722d4b272400ca97a286e20ae4b39ae38275a059b9f0edd4b79e35"
      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whitingdeltix/deltix-cli/releases/download/v0.1.1/uxvalidator_linux_arm64.tar.gz"
      sha256 "ebd69eebdf62f6ffa974141e72174126dba32f6908dcb6c87631fa7e0a74a6a5"
      define_method(:install) do
        bin.install "uxvalidator"
      end
    end
  end
end
